export const talents = [
  {
    name: "Talent Path 1",
    skills: [
      {
        id: 0,
        name: "chevrons",
        icon: "chevrons",
        alt: "Chevrons Icon",
        point: 1,
        active: false,
      },
      {
        id: 1,
        name: "silverware",
        icon: "silverware",
        alt: "Silverware Icon",
        point: 1,
        active: false,
      },
      {
        id: 2,
        name: "cake",
        icon: "cake",
        alt: "Cake Icon",
        point: 1,
        active: false,
      },
      {
        id: 3,
        name: "crown",
        icon: "crown",
        alt: "Crown Icon",
        point: 1,
        active: false,
      },
    ],
  },
  {
    name: "Talent Path 2",
    skills: [
      {
        id: 0,
        name: "boat",
        icon: "boat",
        alt: "Boat Icon",
        point: 1,
        active: false,
      },
      {
        id: 1,
        name: "scuba",
        icon: "scuba",
        alt: "Scuba Icon",
        point: 1,
        active: false,
      },
      {
        id: 2,
        name: "lightning",
        icon: "lightning",
        alt: "Lightning Icon",
        point: 1,
        active: false,
      },
      {
        id: 3,
        name: "skull",
        icon: "skull",
        alt: "Skull Icon",
        point: 1,
        active: false,
      },
    ],
  },
];
